name: Action CI
on:
  push:
    paths-ignore:
      - run_path_*/**

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4.1.1
          - name: Run my own container action
            uses: ./
            with:
              who-to-greet: '@will'
